# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Propesnity Score
#' @return A list with two vectors (`match_id`, `match_x`).
#' @params
#' x
#' @examples
#' set.seed(1231)
#' x <- cbind(runif(5))
#' ps_matching(x)
#' @export
ps_matching <- function(x) {
    .Call(`_egpkg_ps_matching`, x)
}

#' Hello world from Rcpp
#' @return A list with two vectors (`x`, `y`).
#' @examples
#' rcpp_hello_world()
#' @export
rcpp_hello_world <- function() {
    .Call(`_egpkg_rcpp_hello_world`)
}

